- hosts: all
  become: true
  roles:
   - role: commons

- hosts: router
  become: true
  roles:
   - role: router

- hosts: client
  become: true
  roles:
   - role: client

- hosts: web
  become: true
  roles:
   - role: web
   