- hosts: all
  become: true
  roles:
   - role: commons

- hosts: router
  become: true
  roles:
   - role: routers

- hosts: client
  become: true
  roles:
   - role: clients

- hosts: client
  become: true
  roles:
   - role: web
   
