- hosts: all
  become: true
  roles:
   - role: commons

- hosts: routers
  become: true
  roles:
   - role: router

- hosts: clients
  become: true
  roles:
   - role: client

- hosts: clients
  become: true
  roles:
   - role: web
   
