- name: bit de forward
  sysctl: 
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: DNAT redirección puerto 80
  iptables:
    chain: PREROUTING
    destination_port: 80
    in_interface: eth1 
    protocol: tcp
    jump: DNAT
    table: nat
    to_destination: 10.0.0.1:80  
  become: yes

- name: SNAT
  iptables:
    chain: POSTROUTING
    destination: 0.0.0.0/0
    out_interface: eth1
    jump: MASQUERADE
    table: nat
  become: yes