- name: bit de forward
  sysctl: 
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Configuración /etc/network/interfaces del router
  template:
    src: interface
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'

- name: Reiniciar la maquina
  reboot:
